CREATE DATABASE SUCOS;

CREATE TABLE IF NOT EXISTS tbCliente (
CPF VARCHAR(11),
NOME VARCHAR(100),
ENDERECO1 VARCHAR(150),
ENDERECO2 VARCHAR(150),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(50),
CEP VARCHAR(8),
IDADE SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMPRA BIT(1)
);

-- DESAFIO PASSADO NA AULA 03
CREATE TABLE IF NOT EXISTS TABELA_DE_VENDEDORES (
MATRICULA VARCHAR(5),
NOME VARCHAR(100),
PERCENTUAL_COMISSAO FLOAT
);

CREATE TABLE IF NOT EXISTS tbProduto (
PRODUTO VARCHAR(20),
NOME VARCHAR(150),
EMBALAGEM VARCHAR(50),
TAMANHO VARCHAR(50),
SABOR VARCHAR(50),
PRECO_LISTA FLOAT
);

-- CRIANDO TABLE PARA EXCLUIR PRATICA DA AULA
CREATE TABLE TABELA_DE_VENDEDORES2 (
        MATRICULA varchar(5),
        NOME varchar(100),
        PERCENTUAL_COMISSAO float
);

-- DROP DA TABLE ACIMA
drop table if exists TABELA_DE_VENDEDORES2;